# -*- coding: utf-8 -*-
"""First Class.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZSZqnF5gIgaKLXr1E62HAv6hWUm9qAcw
"""

print ('test')

i=10
j=5.5
k="this is my test"
print (i,j,k)

i=10
j=5.5
k="this is my test"
print ('i data type is', type (i),'and value is',i)
print ('j data type is', type (j),'and value is',j)
print ('k data type is', type (k),'and value is',k)

name = input("enter your name: ")
marks_phy = int (input("enter your marks in physics: "))
marks_chem = int (input("enter your marks in chemistry: "))
marks_math = int (input("enter your marks in maths: "))
total = marks_phy + marks_chem + marks_math
percentage = (total/300)*100
print(name, "your total marks are: ", total, "and your percentage is: ", round(percentage,2))
print(f"{name} your total marks are: {total} and your percentage is: {round(percentage,2)}") #same thing as above but here you do not have to add the inverted commas etc again. Only difference is that you need to add an f afer starting the print